apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
  annotations:
    argocd.argoproj.io/sync-wave: "0"  # Pour ArgoCD, cela définit l'ordre de synchronisation
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: beddi006/backend:${BUILD_NUMBER}  # Utiliser la variable d'environnement BUILD_NUMBER
        ports:
        - containerPort: 80
