pipeline {
    agent any
    
    environment {
        DOCKER_IMAGE = "beddi006/backend:${env.BUILD_NUMBER}"
    }

    stages {
        stage('Build') {
            steps {
                script {
                    // Construire l'image Docker et taguer avec BUILD_NUMBER
                    sh "docker build -t ${DOCKER_IMAGE} ./backend/"
                }
            }
        }
        
        stage('Push image') {
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', 'dockerhub') {
                        // Pousser l'image Docker vers Docker Hub
                        sh "docker push ${DOCKER_IMAGE}"
                    }
                }
            }
        }
        
        stage('Deploy') {
            steps {
                echo 'Deploy the application...'
                // Ajoutez vos étapes de déploiement ici
            }
        }
    }
}
