pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub')
        DOCKER_IMAGE = "beddi006/backend:${env.BUILD_NUMBER}"
    }

    stages {
        stage('Docker Login') {
            steps {
                // Ajouter --password-stdin pour exécuter la commande docker login de manière non interactive
                sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
            }
        }
        stage('Build & Push Docker Image with Ansible') {
            steps {
                sh """
                cd Breadcrumbsfish_ops_manager/backend/
                ansible-playbook ansible-playbook.yml -e BUILD_NUMBER=${env.BUILD_NUMBER}
                """
            }
        }
        stage('Deploy') {
            steps {
                echo 'Déployer l\'application...'
                // Ajoutez vos étapes de déploiement ici
            }
        }
    }
}
