pipeline {
    agent any
    
    stages {
        stage('Build') {
            steps {
                script {
                    sh 'docker build -t backend:${env.BUILD_NUMBER} ./backend/'
                }
            }
        }
        
        stage('Push image') {
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', 'dockerhub') {
                        docker.image("backend:${env.BUILD_NUMBER}").push()
                    }
                }
            }
        }
        
        stage('Deploy') {
            steps {
                echo 'Deploy the application...'
                // Ajoutez vos étapes de déploiement ici
            }
        }
    }
}
